#!/usr/bin/env python3
"""Index runs/ into SQLite and optionally ship it to Postgres (DigitalOcean Managed PostgreSQL).

    python3 scripts/db_sync.py --runs-dir runs                       # build/refresh runs/index.sqlite
    python3 scripts/db_sync.py --export-postgres runs/export.postgres.sql
    DATABASE_URL=postgres://... python3 scripts/db_sync.py --push    # needs psycopg or psycopg2

Stdlib only. Prints one JSON line on success (exit 0). `--push` without DATABASE_URL or a driver prints
instructions and exits 2. DATABASE_URL is never printed.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from agent import store  # noqa: E402

SCHEMA_FILE = os.path.join(ROOT, "db", "schema.postgres.sql")


def _redact(message: str, secret: str) -> str:
    if secret and secret in message:
        message = message.replace(secret, "<DATABASE_URL>")
    return message


def write_export(db_path: str, out_path: str) -> int:
    parent = os.path.dirname(os.path.abspath(out_path))
    if parent and not os.path.isdir(parent):
        os.makedirs(parent, exist_ok=True)
    n = 0
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("-- generated by scripts/db_sync.py from %s\n" % db_path)
        fh.write("-- apply db/schema.postgres.sql first; then: psql \"$DATABASE_URL\" -f %s\n" % out_path)
        fh.write("BEGIN;\n")
        for stmt in store.export_postgres_sql(db_path):
            fh.write(stmt)
            fh.write("\n")
            n += 1
        fh.write("COMMIT;\n")
    return n


def push(db_path: str) -> dict:
    """Apply the schema, then run every export statement in one transaction. Raises on failure."""
    url = os.environ.get("DATABASE_URL") or ""
    driver = store._postgres_driver()
    if not url or driver is None:
        raise SystemExit(_push_instructions(url, driver))
    with open(SCHEMA_FILE, encoding="utf-8") as fh:
        schema_sql = fh.read()
    if driver == "psycopg":
        import psycopg  # type: ignore

        connect = psycopg.connect
    else:
        import psycopg2  # type: ignore

        connect = psycopg2.connect
    n = 0
    conn = connect(url)
    try:
        cur = conn.cursor()
        cur.execute(schema_sql)
        for stmt in store.export_postgres_sql(db_path):
            cur.execute(stmt)
            n += 1
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
    return {"driver": driver, "statements": n}


def _push_instructions(url: str, driver: str | None) -> str:
    lines = ["cannot push to Postgres:"]
    if not url:
        lines.append("  - DATABASE_URL is not set. On DigitalOcean: create a Managed PostgreSQL cluster, copy its")
        lines.append("    connection string (with sslmode=require) and export it as DATABASE_URL (a SECRET env var on App Platform).")
    if driver is None:
        lines.append("  - neither psycopg nor psycopg2 is importable: `.venv/bin/pip install 'psycopg[binary]'`.")
    lines.append("  Alternative without a driver: scripts/db_sync.py --export-postgres runs/export.postgres.sql, then")
    lines.append("    psql \"$DATABASE_URL\" -f db/schema.postgres.sql && psql \"$DATABASE_URL\" -f runs/export.postgres.sql")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--runs-dir", default="runs", help="directory with <run_id>/ and eval-*/ folders (default: runs)")
    ap.add_argument("--sqlite", default=None, help="SQLite index path (default: <runs-dir>/index.sqlite)")
    ap.add_argument("--export-postgres", metavar="FILE.sql", default=None,
                    help="write Postgres upsert statements for the whole index to FILE.sql")
    ap.add_argument("--push", action="store_true",
                    help="apply db/schema.postgres.sql and upsert all rows into $DATABASE_URL in one transaction")
    ap.add_argument("--no-sync", action="store_true", help="skip re-indexing runs/ (export/push the existing index)")
    args = ap.parse_args(argv)

    db_path = args.sqlite or store.default_db_path(args.runs_dir)
    out: dict = {"ok": True, "db": "sqlite:%s" % db_path}
    if not args.no_sync:
        out.update(store.sync(args.runs_dir, db_path))
    else:
        st = store.status(db_path)
        out.update({"runs": st["rows"]["runs"], "evals": st["rows"]["evals"], "cases": st["rows"]["cases"]})

    if args.export_postgres:
        out["export"] = {"file": args.export_postgres, "statements": write_export(db_path, args.export_postgres)}

    if args.push:
        url = os.environ.get("DATABASE_URL") or ""
        try:
            out["push"] = push(db_path)
        except SystemExit as exc:
            print(str(exc), file=sys.stderr)
            return 2
        except Exception as exc:  # driver / network / SQL errors; never echo the URL
            print("push failed: %s: %s" % (type(exc).__name__, _redact(str(exc), url)), file=sys.stderr)
            return 1

    print(json.dumps(out, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
