#!/usr/bin/env python3
"""Print a Python dict literal of serverless-inference prices: {inference_id: (input_per_1k, output_per_1k)}.

Stdlib only. Reads DIGITALOCEAN_ACCESS_TOKEN from the environment (never printed), calls
GET https://api.digitalocean.com/v2/gen-ai/models?per_page=200 and converts the per-token USD prices
(`input_price_per_million` / `output_price_per_million` fields are documented per million but the API
returns USD per token) to USD per 1k tokens. Paste the output into agent/metrics.py's price table.

    . scripts/env.sh && make prices-refresh
"""
import json
import os
import sys
import urllib.error
import urllib.request

API_URL = "https://api.digitalocean.com/v2/gen-ai/models?per_page=200"

# Display name (as returned by the models API) -> inference id accepted by inference.do-ai.run/v1.
NAME_TO_INFERENCE_ID = {
    "OpenAI GPT-4o mini": "openai-gpt-4o-mini",
    "OpenAI GPT-4o": "openai-gpt-4o",
    "OpenAI GPT-4.1": "openai-gpt-4.1",
    "OpenAI GPT-5": "openai-gpt-5",
    "OpenAI GPT-5 Mini": "openai-gpt-5-mini",
    "OpenAI GPT-5 Nano": "openai-gpt-5-nano",
    "OpenAI GPT-oss-120b": "openai-gpt-oss-120b",
    "OpenAI GPT-oss-20b": "openai-gpt-oss-20b",
    "Anthropic Claude Haiku 4.5": "anthropic-claude-haiku-4.5",
    "Anthropic Claude 4.5 Sonnet": "anthropic-claude-4.5-sonnet",
    "Anthropic Claude Sonnet 5": "anthropic-claude-5-sonnet",
    "Gemma 4": "gemma-4-31B-it",
    "Ministral 3 14B": "mistral-3-14B",
}


def fetch_models(token):
    req = urllib.request.Request(API_URL, headers={"Authorization": "Bearer " + token, "Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.load(resp).get("models", [])
    except urllib.error.HTTPError as e:
        # Do not dump the response body or headers: they may echo request details.
        sys.exit("models API returned HTTP %s" % e.code)
    except urllib.error.URLError as e:
        sys.exit("models API unreachable: %s" % e.reason)


def _inference_id(model):
    name = (model.get("name") or "").strip()
    if name in NAME_TO_INFERENCE_ID:
        return NAME_TO_INFERENCE_ID[name]
    # Newer API payloads may carry the id directly.
    return model.get("inference_name") or None


def main():
    token = os.environ.get("DIGITALOCEAN_ACCESS_TOKEN", "").strip()
    if not token:
        sys.exit("DIGITALOCEAN_ACCESS_TOKEN is not set (try: . scripts/env.sh)")

    prices = {}
    skipped = []
    for model in fetch_models(token):
        pricing = model.get("pricing") or {}
        if pricing.get("input_price_per_million") is None:
            continue
        inference_id = _inference_id(model)
        if not inference_id:
            skipped.append(model.get("name") or "?")
            continue
        per_token_in = float(pricing["input_price_per_million"])
        per_token_out = float(pricing.get("output_price_per_million") or 0.0)
        prices[inference_id] = (round(per_token_in * 1000, 6), round(per_token_out * 1000, 6))

    print("# USD per 1k tokens (input, output) - generated by scripts/refresh_prices.py")
    print("PRICES_PER_1K = {")
    for inference_id in sorted(prices):
        print("    %r: %r," % (inference_id, prices[inference_id]))
    print("}")
    if skipped:
        print("# priced models without a known inference id (add to NAME_TO_INFERENCE_ID): %s"
              % ", ".join(sorted(skipped)), file=sys.stderr)


if __name__ == "__main__":
    main()
